[GECO-19] Add REST endpoint to change document access
diging/giles-eco-giles-web pull request #26
Opened 2017-03-11 00:00 UTC by snilapwa

2017-03-11 00:37 UTC, jdamerow requested changes

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +        if (docId == null || docId.isEmpty() || access == null || access.isEmpty()) {
docId can never be null, if docId is not provided the path does not match and the method isn't called.

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +        if (docId == null || docId.isEmpty() || access == null || access.isEmpty()) {
I'm fairly sure that if access isn't provided in the request, then Spring will throw an exception. Have you tested that?

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +            }
I'd return a bad request here, not throwing an exception. That's not an unexpected case.

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +            }
wait, why are you throwing an exception just to catch it right away? doesn't make sense.

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +        }
duplicate code. all of this should be moved to the manager class and then reused by the other controller that's changing the access of a document through the webapp GUI.

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +                    HttpStatus.INTERNAL_SERVER_ERROR);
that's not an internal server error, but a bad request.

2017-03-11 00:37 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +        }
the same thing is checked in the controller method. is this method checking anything else that the giles token check doesn't do? If not, remove this method and just use ```TokenCheck``` annotation like the other methods.

2017-03-16 17:00 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +        if (docId == null || docId.isEmpty() || access == null || access.isEmpty()) {
corrected.

2017-03-16 17:00 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +            }
corrected

2017-03-16 17:00 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +                    HttpStatus.INTERNAL_SERVER_ERROR);
corrected

2017-03-16 17:00 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +        }
done

2017-03-16 17:00 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +        }
removed doc null check from controller. With token check, this method also check for document owner. User requesting document access change should be owner of the document irrespective of current access type. We have previous DocumentAccessCheck annotation but it does not check document owner for public documents.

2017-03-16 17:46 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +        }
still, a lot of code duplication. Just check for the owner in the controller method.

2017-03-16 17:54 UTC, jdamerow requested changes

2017-03-16 17:54 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/files/IFilesManager.java
> +    public abstract boolean changeDocumentAccess(IDocument doc, DocumentAccess docAccess) throws UnstorableObjectException;
this should return "true" when action was executed successfully, otherwise false. The way it is right now is not very intuitive.

2017-03-16 17:54 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/files/IFilesManager.java
> +    public abstract boolean changeDocumentAccess(IDocument doc, DocumentAccess docAccess) throws UnstorableObjectException;
javadoc missing

2017-03-16 17:54 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/files/impl/FilesManager.java
> +    public boolean changeDocumentAccess(IDocument doc, DocumentAccess docAccess) throws UnstorableObjectException {
needs a test (at least for this method, preferably for the whole class).

2017-03-24 18:27 UTC, jdamerow requested changes

2017-03-24 18:27 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/files/impl/FilesManager.java
> +            }
let's create a submethod for this and call it for each type of file.

2017-03-24 18:27 UTC, jdamerow commented on giles-eco/src/test/java/edu/asu/diging/gilesecosystem/web/files/impl/FilesManagerTest.java
> +    IDocument doc = null;
should be private

2017-03-24 18:27 UTC, jdamerow commented on giles-eco/src/test/java/edu/asu/diging/gilesecosystem/web/files/impl/FilesManagerTest.java
> +    private DocumentAccess accessPublic = DocumentAccess.PUBLIC;
given those are just enums, you might as well use them directly (this is just the same thing in other words accessPrivate = DocumentAccess.PRIVATE)

2017-03-24 18:27 UTC, jdamerow commented on giles-eco/src/test/java/edu/asu/diging/gilesecosystem/web/files/impl/FilesManagerTest.java
> +        Assert.assertEquals(doc.getAccess(), accessPublic);
what about the attached pages? You need to make sure they are changed as well (that's the business logic you want to test).

2017-03-24 18:27 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/files/IFilesManager.java
> +     * This method changes document access type to provided new access type
it also changes the document access of the files attached as pages!

2017-03-24 20:51 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/files/impl/FilesManager.java
> +                }
you can shorten those if's as
```
isChangeSuccess = isChangeSuccess && changeFile...
```

2017-03-24 21:06 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +    public ResponseEntity<String> changeDocumentAccess(@RequestParam(defaultValue = "") String accessToken,
method should be in it's own file and access parameter should be case-insensitive. (it shouldn't matter if user submits "private" or "PRIVATE".

2017-03-24 21:07 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/FilesController.java
> +        return new ResponseEntity<String>(HttpStatus.OK);
there needs to be a return message.

2017-03-27 16:46 UTC, jdamerow approved these changes

2017-03-27 16:46 UTC, merged