[GECO-44] find image file with and without preceding slash
diging/giles-eco-giles-web pull request #34
Opened 2017-04-14 19:47 UTC by snilapwa

2017-04-14 21:07 UTC, jdamerow requested changes

2017-04-14 21:07 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +                    }
make that a ternary operator

2017-04-14 21:07 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/DigilibPassthroughController.java
> +            }
same here

2017-04-14 21:23 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +                    }
changed

2017-04-14 21:23 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/rest/DigilibPassthroughController.java
> +            }
changed

2017-04-19 15:43 UTC, jdamerow commented
ok to test

2017-04-19 15:43 UTC, jdamerow approved these changes

2017-04-19 15:47 UTC, merged