[GECO-48] send errors to September
diging/giles-eco-giles-web pull request #36
Opened 2017-04-20 17:16 UTC by snilapwa

2017-04-21 16:57 UTC, jdamerow requested changes

2017-04-21 16:57 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +    private GilesTokenConfig tokenConfig;
why are you autowiring a config class?

2017-04-21 16:57 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +    private GilesTokenConfig tokenConfig;
autowire the message hander directly

2017-04-21 16:57 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/tokens/impl/GitHubChecker.java
> +            tokenConfig.getMessageHandler().handleError("Could not authenticate user with GitHub", ex);
this needs to be logged as a warning

2017-04-21 16:57 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +    private GilesTokenConfig tokenConfig;
same is true for all classes

2017-04-21 16:57 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +    private GilesTokenConfig tokenConfig;
also, GilesTokenConfig needs a better name if it does not only contain configurations for tokens

2017-04-21 17:03 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +    private GilesTokenConfig tokenConfig;
and since the message handler logs error, they shouldn't be logged before the handler is called.

2017-04-21 21:04 UTC, snilapwa commented
update september-util package before test

2017-04-25 18:48 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/aspects/access/RestSecurityAspect.java
> +    private SystemMessageHandler messageHandler;
isn't there an interface for that class? use that one.

2017-04-28 15:41 UTC, snilapwa commented
need to merge after https://github.com/diging/giles-eco-september-util/pull/4 gets merged

2017-04-29 00:12 UTC, jdamerow commented
ok to test

2017-04-29 00:12 UTC, jdamerow approved these changes

2017-04-29 00:24 UTC, jdamerow commented
test cases are failing (you can discard the couln't create native thread one).

2017-05-01 17:15 UTC, snilapwa commented
@jdamerow updated test cases

2017-05-01 17:52 UTC, merged