[GECO-22] send notification to admin when new user registers
diging/giles-eco-giles-web pull request #38
Opened 2017-05-01 21:54 UTC by snilapwa

2017-05-01 21:55 UTC, snilapwa commented
Verified with test gmail account values in email-config.xml

2017-05-01 23:23 UTC, jdamerow requested changes

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/email/impl/EmailNotificationManager.java
> +        } catch (Exception e) {
is this really throwing exception? if so, please make a comment.

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/email/impl/EmailNotificationSender.java
> +public class EmailNotificationSender {
needs interface

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/email/impl/EmailNotificationSender.java
> +    }
are those getters and setters used anywhere? if not, delete.

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/exceptions/GilesNotificationException.java
> +public class GilesNotificationException extends Exception {
let's add javadoc

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +            } catch (Exception e) {
why is this catching Exception? It's not throwing Exception, is it?

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +        if(user.getRoles().contains(GilesRole.ROLE_ADMIN.name())) {
this should never be the case. when a user is first approved, it should not have the admin role yet.

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +        if(user.getRoles().contains(GilesRole.ROLE_ADMIN.name())) {
is there a reason, you've added this?

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +        if(role == GilesRole.ROLE_ADMIN) {
why are you adding this? is there are reason you're not using the roles to decide if a user is an admin?

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +        if(role == GilesRole.ROLE_ADMIN) {
same as above.

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/webapp/WEB-INF/spring/email-config.xml
> +    </bean>
I would not use XML here, use java annotation. You can simply read the values from a properties file.

2017-05-01 23:23 UTC, jdamerow commented on giles-eco/src/main/webapp/WEB-INF/spring/root-context.xml
> +
there is already  amessage source defined, why don't you use that one instead of loading the same file again?

2017-05-02 17:01 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/email/impl/EmailNotificationManager.java
> +        } catch (Exception e) {
Yes, VelocityEngine.getTemplate call need to throw Exception

2017-05-02 17:05 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +            } catch (Exception e) {
It is throwing GilesNotificationException

2017-05-02 17:47 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +            } catch (Exception e) {
then why are you catching Exception?

2017-05-02 17:47 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/email/impl/EmailNotificationManager.java
> +        } catch (Exception e) {
then please make a comment here

2017-05-02 21:43 UTC, jdamerow requested changes

2017-05-02 21:43 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/exceptions/GilesNotificationException.java
> + * The purpose of this class is to manage all notification exceptions.
this is an exception class. It doesn't manage anything.

2017-05-02 21:43 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +                messageHandler.handleMessage("Email to " + admin.getUsername() + " could not be sent.", e, MessageType.ERROR);
let's make that a warning. It doesn't crash the system or anything, but could happen.

2017-05-02 22:00 UTC, snilapwa commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/users/UsersManager.java
> +                messageHandler.handleMessage("Email to " + admin.getUsername() + " could not be sent.", e, MessageType.ERROR);
Done

2017-05-03 15:55 UTC, jdamerow requested changes

2017-05-03 15:55 UTC, jdamerow commented on giles-eco/pom.xml
> +            <version>1.5</version>
let's use the latest version here

2017-05-03 15:55 UTC, jdamerow commented on giles-eco/src/main/java/edu/asu/diging/gilesecosystem/web/email/IEmailNotificationManager.java
> +    void sendAccountCreatedEmail(String name, String username, String adminName, String adminEmail)
javadoc missing

2017-05-03 15:56 UTC, jdamerow commented
ok, cool. just a few little things.

2017-05-03 16:24 UTC, snilapwa commented
@jdamerow updated code as per review comments

2017-05-03 17:56 UTC, jdamerow approved these changes

2017-05-03 17:58 UTC, jdamerow commented
ok to test

2017-05-03 18:01 UTC, merged